config/routes.rb
Cookier::Application.routes.draw do
  get "welcome/index"

  resources :site_sales

  resources :cookies

  root :to => 'welcome#index'

end

app/models/cookie.rb
class Cookie < ActiveRecord::Base
  has_many :cookie_counts
  attr_accessible :name
end

app/models/cookie_count.rb
class CookieCount < ActiveRecord::Base
  belongs_to :cookie
  belongs_to :site_sale

  attr_accessible :cookie_id, :quantity, :site_sale_id, :type

end

app/models/mom_start_count.rb
class MomStartCount < CookieCount

end

app/models/site_end_count.rb
class SiteEndCount < CookieCount

end

app/models/site_sale.rb
class SiteSale < ActiveRecord::Base
  has_many :cookie_counts
  has_many :cookies, :through => :cookie_counts

  attr_accessible :end_at, :location, :start_at
end

app/models/site_start_count.rb
class SiteStartCount < CookieCount

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  # GET /cookies
  # GET /cookies.json
  def index
    @cookies = Cookie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cookies }
    end
  end

  # GET /cookies/1
  # GET /cookies/1.json
  def show
    @cooky = Cookie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cooky }
    end
  end

  # GET /cookies/new
  # GET /cookies/new.json
  def new
    @cooky = Cookie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cooky }
    end
  end

  # GET /cookies/1/edit
  def edit
    @cooky = Cookie.find(params[:id])
  end

  # POST /cookies
  # POST /cookies.json
  def create
    @cooky = Cookie.new(params[:cooky])

    respond_to do |format|
      if @cooky.save
        format.html { redirect_to @cooky, notice: 'Cookie was successfully created.' }
        format.json { render json: @cooky, status: :created, location: @cooky }
      else
        format.html { render action: "new" }
        format.json { render json: @cooky.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cookies/1
  # PUT /cookies/1.json
  def update
    @cooky = Cookie.find(params[:id])

    respond_to do |format|
      if @cooky.update_attributes(params[:cooky])
        format.html { redirect_to @cooky, notice: 'Cookie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cooky.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookies/1
  # DELETE /cookies/1.json
  def destroy
    @cooky = Cookie.find(params[:id])
    @cooky.destroy

    respond_to do |format|
      format.html { redirect_to cookies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/site_sales_controller.rb
class SiteSalesController < ApplicationController
  # GET /site_sales
  # GET /site_sales.json
  def index
    @site_sales = SiteSale.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @site_sales }
    end
  end

  # GET /site_sales/1
  # GET /site_sales/1.json
  def show
    @site_sale = SiteSale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site_sale }
    end
  end

  # GET /site_sales/new
  # GET /site_sales/new.json
  def new
    @site_sale = SiteSale.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site_sale }
    end
  end

  # GET /site_sales/1/edit
  def edit
    @site_sale = SiteSale.find(params[:id])
  end

  # POST /site_sales
  # POST /site_sales.json
  def create
    @site_sale = SiteSale.new(params[:site_sale])

    respond_to do |format|
      if @site_sale.save
        format.html { redirect_to @site_sale, notice: 'Site sale was successfully created.' }
        format.json { render json: @site_sale, status: :created, location: @site_sale }
      else
        format.html { render action: "new" }
        format.json { render json: @site_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /site_sales/1
  # PUT /site_sales/1.json
  def update
    @site_sale = SiteSale.find(params[:id])

    respond_to do |format|
      if @site_sale.update_attributes(params[:site_sale])
        format.html { redirect_to @site_sale, notice: 'Site sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_sales/1
  # DELETE /site_sales/1.json
  def destroy
    @site_sale = SiteSale.find(params[:id])
    @site_sale.destroy

    respond_to do |format|
      format.html { redirect_to site_sales_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/site_sales_helper.rb
module SiteSalesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cookies/_form.html.erb
<%= form_for(@cooky) do |f| %>
  <% if @cooky.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cooky.errors.count, "error") %> prohibited this cooky from being saved:</h2>

      <ul>
      <% @cooky.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cookies/edit.html.erb
<h1>Editing cooky</h1>

<%= render 'form' %>

<%= link_to 'Show', @cooky %> |
<%= link_to 'Back', cookies_path %>

app/views/cookies/index.html.erb
<h1>Listing cookies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cookies.each do |cooky| %>
  <tr>
    <td><%= cooky.name %></td>
    <td><%= link_to 'Show', cooky %></td>
    <td><%= link_to 'Edit', edit_cooky_path(cooky) %></td>
    <td><%= link_to 'Destroy', cooky, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cookie', new_cooky_path %>

app/views/cookies/new.html.erb
<h1>New cooky</h1>

<%= render 'form' %>

<%= link_to 'Back', cookies_path %>

app/views/cookies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @cooky.name %>
</p>


<%= link_to 'Edit', edit_cooky_path(@cooky) %> |
<%= link_to 'Back', cookies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookier</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/site_sales/_form.html.erb
<%= form_for(@site_sale) do |f| %>
  <% if @site_sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site_sale.errors.count, "error") %> prohibited this site_sale from being saved:</h2>

      <ul>
      <% @site_sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br />
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br />
    <%= f.datetime_select :end_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/site_sales/edit.html.erb
<h1>Editing site_sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @site_sale %> |
<%= link_to 'Back', site_sales_path %>

app/views/site_sales/index.html.erb
<h1>Listing site_sales</h1>

<table>
  <tr>
    <th>Location</th>
    <th>Start at</th>
    <th>End at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @site_sales.each do |site_sale| %>
  <tr>
    <td><%= site_sale.location %></td>
    <td><%= site_sale.start_at %></td>
    <td><%= site_sale.end_at %></td>
    <td><%= link_to 'Show', site_sale %></td>
    <td><%= link_to 'Edit', edit_site_sale_path(site_sale) %></td>
    <td><%= link_to 'Destroy', site_sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site sale', new_site_sale_path %>

app/views/site_sales/new.html.erb
<h1>New site_sale</h1>

<%= render 'form' %>

<%= link_to 'Back', site_sales_path %>

app/views/site_sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Location:</b>
  <%= @site_sale.location %>
</p>

<p>
  <b>Start at:</b>
  <%= @site_sale.start_at %>
</p>

<p>
  <b>End at:</b>
  <%= @site_sale.end_at %>
</p>


<%= link_to 'Edit', edit_site_sale_path(@site_sale) %> |
<%= link_to 'Back', site_sales_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Moms Start Inventory: <%= MomStartCount.sum(:quantity) %></p>
<p>Cookies Checked Out: <%= SiteStartCount.sum(:quantity) %></p>
<p>Cookies Checked In: <%= SiteEndCount.sum(:quantity) %></p>
<p>Running Inventory: <%= (MomStartCount.sum(:quantity)-SiteStartCount.sum(:quantity))+SiteEndCount.sum(:quantity) %></p>